apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      monitor: todo-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: web
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-container-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todo-backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: backend-port
    interval: 30s
